plugins {
    id 'com.axelor.app'
}

axelor {
    title "Axelor Music Store"
}

dependencies {
    api project(":modules:axelor-base")

    compileOnly 'org.projectlombok:lombok:1.18.24'
    annotationProcessor 'org.projectlombok:lombok:1.18.24'
    implementation 'org.thymeleaf:thymeleaf:3.0.15.RELEASE'
    implementation 'com.itextpdf:itextpdf:5.5.13.4'
    implementation 'com.itextpdf:html2pdf:5.0.2'
    implementation 'org.json:json:20240303'
}